### ISSUE TITLE
"Editar professor" cria cópia do usuário editado

### ISSUE THREAD

**Issue by Caiodzj94116** [ufba-facil/colegiado#3]
Ao editar um perfil de professor na lista e alterar seu usuário, uma nova entrada na lista é criada.

### Como reproduzir:
1. Acesse lac.ufba.br/teacher
2. Clique em "Editar" ao lado de qualquer perfil
3. Altere o nome de usuário e clique em "Salvar"
4. Clique em "Lista de professores". Um novo perfil com o nome alterado deve ter surgido.

Caso o nome alterado já exista, um perfil duplicado é criado.

**Comment by naaramusse** [comment]
A função de update ainda não estava pronta, então a rota estava indo para a função store.
Já foi resolvido.

**Comment by Caiodzj94116** [comment]
@naaramusse como você disse, está funcionando corretamente. Estou fechando a issue.
